apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: my-apps
  labels:
    app: postgres
data:
  POSTGRES_DB: admin
  POSTGRES_USER: admin
  POSTGRES_HOST: pg-svc
  POSTGRES_PORT: '5432'