apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: salamy1/dwk-pingpong:v13
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts: 
            - name: shared-file
              mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: pg-dbpass
                    key: POSTGRES_PASSWORD
      volumes:
        - name: shared-file
          persistentVolumeClaim:
              claimName: hash-claim