apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hash-claim
  namespace: my-apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi